[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[dependencies]
memory = { path = "memory" }

[target.x86_64-unknown-kernel.dependencies]
multiboot2 = { path = "multiboot2"}

[profile.dev]
opt-level = 2

[profile.release]
opt-level = "z"
lto = true
strip = true
